web:
  developer: "Apache"
  ram: 128
  cpu: 0.12
  storage: 100
  metadata:
    content: "blog"
game:
  developer: "Microsoft"
  ram: 1024
  cpu: 1
  storage: 500
  metadata:
    rating: "T"
database:
  developer: "Oracle"
  ram: 256
  cpu: 0.12
  storage: 1024
  metadata:
    content: "movies"